package reports

import (
	"fmt"
	"strings"
	"time"

	"github.com/libyan-cooperation-org/OBLIVRA-Sovereign-SIEM-/internal/storage/sqlitestore"
	"github.com/libyan-cooperation-org/OBLIVRA-Sovereign-SIEM-/pkg/models"
)

type Manager struct {
	store *sqlitestore.DB
}

func NewManager(store *sqlitestore.DB) *Manager {
	return &Manager{store: store}
}

// GenerateCaseReport produces a human-readable investigation summary in Markdown.
func (m *Manager) GenerateCaseReport(caseID string) (string, error) {
	c, alerts, comments, err := m.getCaseDetails(caseID)
	if err != nil {
		return "", err
	}

	evidence, err := m.store.GetEvidenceForCase(caseID)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# Investigation Report: %s\n\n", c.Title))
	b.WriteString(fmt.Sprintf("## Executive Summary\n"))
	b.WriteString(fmt.Sprintf("- **Case ID:** %s\n", c.ID))
	b.WriteString(fmt.Sprintf("- **Severity:** %s\n", strings.ToUpper(c.Severity)))
	b.WriteString(fmt.Sprintf("- **Status:** %s\n", strings.ToUpper(c.Status)))
	b.WriteString(fmt.Sprintf("- **Assignee:** %s\n", c.Assignee))
	b.WriteString(fmt.Sprintf("- **Created At:** %s\n", c.CreatedAt.Format(time.RFC1123)))
	b.WriteString(fmt.Sprintf("\n### Description\n%s\n\n", c.Description))

	b.WriteString("## Timeline of Alerts\n")
	if len(alerts) == 0 {
		b.WriteString("*No alerts linked to this case.*\n")
	} else {
		for _, a := range alerts {
			b.WriteString(fmt.Sprintf("- [%s] **%s**: %s (Severity: %s)\n",
				a.Timestamp.Format("15:04:05"), a.Title, a.Summary, a.Severity))
		}
	}
	b.WriteString("\n")

	b.WriteString("## Analyst Comments\n")
	if len(comments) == 0 {
		b.WriteString("*No comments recorded.*\n")
	} else {
		for _, com := range comments {
			b.WriteString(fmt.Sprintf("### %s (%s)\n%s\n\n",
				com.Author, com.CreatedAt.Format("2006-01-02 15:04"), com.Text))
		}
	}

	b.WriteString("## Forensic Evidence Locker\n")
	if len(evidence) == 0 {
		b.WriteString("*No forensic evidence captured for this case.*\n")
	} else {
		b.WriteString("| Captured At | Recorded By | Event ID | SHA-256 Hash | Reason |\n")
		b.WriteString("|-------------|-------------|----------|--------------|--------|\n")
		for _, e := range evidence {
			shortHash := e.RawHash
			if len(shortHash) > 16 {
				shortHash = shortHash[:16] + "..."
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s | `%s` | %s |\n",
				e.CreatedAt.Format("2006-01-02 15:04"), e.RecordedBy, e.EventID, shortHash, e.Reason))
		}
	}

	b.WriteString("\n---\n*Report generated by OBLIVRA Sovereign SIEM Forensics Engine*")

	return b.String(), nil
}

func (m *Manager) getCaseDetails(caseID string) (*sqlitestore.CaseRecord, []*models.Alert, []*sqlitestore.CaseComment, error) {
	c, err := m.store.GetCase(caseID)
	if err != nil {
		return nil, nil, nil, err
	}
	if c == nil {
		return nil, nil, nil, fmt.Errorf("case not found")
	}

	alerts, err := m.store.GetAlertsForCase(caseID)
	if err != nil {
		return nil, nil, nil, err
	}

	comments, err := m.store.ListCaseComments(caseID)
	if err != nil {
		return nil, nil, nil, err
	}

	return c, alerts, comments, nil
}
