// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEvidence(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddEvidence'](arg1, arg2, arg3);
}

export function GenerateReport(arg1) {
  return window['go']['app']['App']['GenerateReport'](arg1);
}

export function GetAlertCounts() {
  return window['go']['app']['App']['GetAlertCounts']();
}

export function GetAlertGraph(arg1) {
  return window['go']['app']['App']['GetAlertGraph'](arg1);
}

export function GetComplianceCoverage() {
  return window['go']['app']['App']['GetComplianceCoverage']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetCurrentUser() {
  return window['go']['app']['App']['GetCurrentUser']();
}

export function GetStorageStats() {
  return window['go']['app']['App']['GetStorageStats']();
}

export function ListAgents() {
  return window['go']['app']['App']['ListAgents']();
}

export function ListAlerts(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListAlerts'](arg1, arg2, arg3);
}

export function ListAssets(arg1) {
  return window['go']['app']['App']['ListAssets'](arg1);
}

export function ListAuditLogs(arg1) {
  return window['go']['app']['App']['ListAuditLogs'](arg1);
}

export function ListCases(arg1, arg2) {
  return window['go']['app']['App']['ListCases'](arg1, arg2);
}

export function ListRules(arg1) {
  return window['go']['app']['App']['ListRules'](arg1);
}

export function ListSavedSearches() {
  return window['go']['app']['App']['ListSavedSearches']();
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function SaveSearch(arg1, arg2) {
  return window['go']['app']['App']['SaveSearch'](arg1, arg2);
}

export function SearchEvents(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['SearchEvents'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function UpdateAlertStatus(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateAlertStatus'](arg1, arg2, arg3);
}

export function UpdateCaseStatus(arg1, arg2) {
  return window['go']['app']['App']['UpdateCaseStatus'](arg1, arg2);
}
