// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graph} from '../models';
import {config} from '../models';
import {sqlitestore} from '../models';
import {storage} from '../models';
import {models} from '../models';
import {context} from '../models';

export function AddEvidence(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GenerateReport(arg1:string):Promise<string>;

export function GetAlertCounts():Promise<Record<string, number>>;

export function GetAlertGraph(arg1:string):Promise<graph.Graph>;

export function GetComplianceCoverage():Promise<Record<string, number>>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentUser():Promise<sqlitestore.UserRecord>;

export function GetStorageStats():Promise<storage.StorageStats>;

export function ListAgents():Promise<Array<sqlitestore.AgentRecord>>;

export function ListAlerts(arg1:string,arg2:string,arg3:number):Promise<Array<models.Alert>>;

export function ListAssets(arg1:number):Promise<Array<sqlitestore.AssetRecord>>;

export function ListAuditLogs(arg1:number):Promise<Array<sqlitestore.AuditRecord>>;

export function ListCases(arg1:string,arg2:number):Promise<Array<sqlitestore.CaseRecord>>;

export function ListRules(arg1:boolean):Promise<Array<sqlitestore.RuleRecord>>;

export function ListSavedSearches():Promise<Array<models.SavedSearch>>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Logout():Promise<void>;

export function SaveSearch(arg1:string,arg2:string):Promise<models.SavedSearch>;

export function SearchEvents(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number):Promise<Array<models.Event>>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function UpdateAlertStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateCaseStatus(arg1:string,arg2:string):Promise<void>;
